### ISSUE TITLE
Unable to start owp

### ISSUE THREAD

**Issue by alex3137** [sibprogrammer/owp#52]
Hello.

owp was working fine until I tried to connect to it. I wanted to restart it, here is the output of /etc/init.d/owp restart: 

root[/home/alex]# /etc/init.d/owp restart
Stopping OpenVZ Web Panel server...
Stopping hardware node daemon...
[FAIL] Unable to stop hardware node daemon.
Stopping watchdog daemon...
[FAIL] Unable to stop watchdog daemon.
Starting OpenVZ Web Panel...
Starting watchdog daemon...
[FAIL] Unable to start watchdog daemon.
Starting web server webrick on 0.0.0.0:3000...
[FAIL] Unable to start web server.
Starting hardware node daemon...
[FAIL] Unable to start hardware node daemon.
Syncing hardware nodes states...
[FAIL] Unable to sync information about hardware nodes.

Any clue what to try / where to look ?

**Comment by sibprogrammer** [comment]
Most probably it means lack of resources (RAM).

**Comment by alex3137** [comment]
No I have plenty of RAM left (1 GB+). Actually the problem is I updated to Ruby 1.9 but owp seems only compatible with Ruby 1.8.

Would it be possible to make it compatible with more recent versions of Ruby ?

**Comment by cybernet** [comment]
+1

**Comment by afiskon** [comment]
Same issue here

```
$ ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

$ cat /etc/redhat-release 
CentOS release 6.6 (Final)
```

You can easily reproduce it by creating centos6 box in Vagrant and trying to install owp according to Installation section at http://owp.softunity.com.ru/

**Comment by afiskon** [comment]
For the record: I have found a workaround. You can remove `> /dev/null 2>&1` code from /etc/init.d/owp script to see error messages. In my case it was:

```
/opt/ovz-web-panel//script/../config/../vendor/rails/railties/lib/rails/gem_dependency.rb:21:in `add_frozen_gem_path': undefined method `source_index' for Gem:Module (NoMethodError)
	from /opt/ovz-web-panel//script/../config/../vendor/rails/railties/lib/initializer.rb:273:in `add_gem_load_paths'
	from /opt/ovz-web-panel//script/../config/../vendor/rails/railties/lib/initializer.rb:131:in `process'
	from /opt/ovz-web-panel//script/../config/../vendor/rails/railties/lib/initializer.rb:112:in `send'
	from /opt/ovz-web-panel//script/../config/../vendor/rails/railties/lib/initializer.rb:112:in `run'
	from /opt/ovz-web-panel/config/environment.rb:6
	from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:54:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ovz-web-panel/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `require'
	from /opt/ovz-web-panel/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
	from /opt/ovz-web-panel/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `require'
	from /opt/ovz-web-panel/vendor/rails/railties/lib/commands/servers/webrick.rb:59
	from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:54:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ovz-web-panel/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `require'
	from /opt/ovz-web-panel/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
	from /opt/ovz-web-panel/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `require'
	from /opt/ovz-web-panel/vendor/rails/railties/lib/commands/server.rb:49
	from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:54:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ovz-web-panel//script/server:3
```

Solution was found on stackoverflow: http://stackoverflow.com/questions/15349869/undefined-method-source-index-for-gemmodule-nomethoderror

```
sudo gem update --system 1.8.25
```

Than remove /var/lock/owp to get rid of:

```
[FAIL] OpenVZ Web Panel is already running.
```

... error. Now OWP should start!
